__title__ = "Windows-Toasts"
__description__ = "Python library used to send toast notifications on Windows machines"
__url__ = "https://github.com/DatGuy1/Windows-Toasts"
__version__ = "0.4.1"
__author__ = "DatGuy"
__license__ = "Apache 2.0"
