import datetime

from winsdk.windows.data.xml.dom import IXmlNode, XmlDocument

from .toast_audio import ToastAudio

class ToastDocument:
    xmlDocument: XmlDocument
    def __init__(self, xmlDocument: XmlDocument) -> None: ...
    def SetAttribute(self, nodeAttribute: IXmlNode, attributeName: str, attributeValue: str) -> None: ...
    def SetNodeStringValue(self, targetNode: IXmlNode, newValue: str) -> None: ...
    def SetAttributionText(self, attributionText: str) -> None: ...
    def SetAudioAttributes(self, audioConfiguration: ToastAudio) -> None: ...
    def SetTextField(self, newValue: str, nodePosition: int) -> None: ...
    def SetCustomTimestamp(self, customTimestamp: datetime.datetime): ...
    def SetImageField(self, imagePath: str) -> None: ...
    def SetInputField(self, placeholderText: str) -> None: ...
    def SetDuration(self, duration: str) -> None: ...
    def AddAction(self, buttonContent: str, arguments: str) -> None: ...
