name: Deploy

on:
  push:
    tags:
      # These tags are protected
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

# Set permissions at the job level.
permissions: {}

jobs:
  deploy:
    if: github.repository == 'DatGuy1/Windows-Toasts'

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build github3.py pypandoc
      - name: Build package
        run: |
          python -m build

      - name: Publish GitHub release notes
        env:
          GH_RELEASE_NOTES_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get install pandoc
          python scripts/publish_gh_release_notes.py