name: Tests

on: [push, pull_request]

env:
  PYTEST_ADDOPTS: "--color=yes"

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip, wheel, setuptools, build
      run: |
        python -m pip install -U pip wheel setuptools build twine
    - name: Install testing dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Install self
      run: |
        python -m pip install .
    - name: Generate coverage report
      run: |
        pytest --cov=windows_toasts --cov=scripts/ --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
    - name: Format per black code style
      uses: psf/black@stable
    - name: Order imports
      uses: isort/isort-action@master
    - name: Enforce flake8
      run: flake8