name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip, wheel, setuptools, build
      run: |
        python -m pip install -U pip wheel setuptools build twine
    - name: Install testing dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Install self
      run: |
        python -m pip install .
    - name: Generate coverage report
      run: |
        pytest --cov=windows_toasts --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0